name: hotel_reservation
description: "A new Flutter project."
publish_to: 'none'



environment:
  sdk: '>=3.0.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  freezed_annotation: ^2.4.1
  cloud_firestore: ^4.13.5
  json_annotation: ^4.8.1
  firebase_core: ^2.24.2
  injectable: ^2.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  auto_route: ^7.8.4
  firebase_auth: ^4.15.2
  google_sign_in: ^6.1.6
  get_it: ^7.6.4
  google_sign_in_web: ^0.12.3+1
  provider: ^6.1.1
  file_picker: ^6.1.1
  image_picker: ^1.0.5
  syncfusion_flutter_datepicker: ^23.2.7
  firebase_storage: ^11.5.6
  carousel_slider: ^4.2.1
  calendar_date_picker2: ^0.5.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/