// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBadskN7wEaxSTexyYE-TWbaE79TZQrx_w',
    appId: '1:389826330138:web:bae758b7ea7dc785695ba3',
    messagingSenderId: '389826330138',
    projectId: 'hotel-reservation-15bea',
    authDomain: 'hotel-reservation-15bea.firebaseapp.com',
    storageBucket: 'hotel-reservation-15bea.appspot.com',
    measurementId: 'G-XFS5GQ3FHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB08y7X7sU9rzg-MtWQleiBqd5nl0ep4bU',
    appId: '1:389826330138:android:2ba77431ba61c5e5695ba3',
    messagingSenderId: '389826330138',
    projectId: 'hotel-reservation-15bea',
    storageBucket: 'hotel-reservation-15bea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBawpbUPhQosdfaSMBFmYdQEbClQWeHTyY',
    appId: '1:389826330138:ios:4eb9c90d9b9d05bd695ba3',
    messagingSenderId: '389826330138',
    projectId: 'hotel-reservation-15bea',
    storageBucket: 'hotel-reservation-15bea.appspot.com',
    iosBundleId: 'com.example.hotelReservation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBawpbUPhQosdfaSMBFmYdQEbClQWeHTyY',
    appId: '1:389826330138:ios:b4e90d8aa0b0bc7f695ba3',
    messagingSenderId: '389826330138',
    projectId: 'hotel-reservation-15bea',
    storageBucket: 'hotel-reservation-15bea.appspot.com',
    iosBundleId: 'com.example.hotelReservation.RunnerTests',
  );
}
